### PR TITLE
New front page.

### PR DESCRIPTION
**Pull request by teh**

### CODE REVIEW

**Comment by Keats** [comment]
We'd probably want to remove the techs if we remove web dev

**Comment by teh** [comment]
Maybe replace go with the scipy logo? The rest is still fairly accurate. E.g. when we build a data pipeline there's usually a website at the end to present the data.

**Comment by Keats** [comment]
I'd keep go, but then python should be enough to cover numpy/scipy etc

**Comment by teh** [comment]
OK, I think it's good to have a few links even if not totally accurate (there would be way too many). I don't feel that strongly: Which set would you like to see?

**Comment by Keats** [comment]
we can add numpy or scipy i'd say but we will a retina version

**Comment by teh** [comment]
OK, added the scipy round snake.

**Comment by Keats** [comment]
lgtm, waiting for @Gautier

**Comment by Gautier** [comment]
I like the wording and the set of icons (all of these techs are great and we can really use them). My only comment would be to swap data science and product developement around.

**Comment by teh** [comment]
Sorry I missed your comment gautier. Fixed. Will merge on LGTM.

**Pull request merged**
